from nonebot.adapters.onebot.v11 import Event
from typing import Optional


class Bot:
    async def reset_expire(self, convo_id: str): ...
    async def reset_chat(self, convo_id: str, force: bool): ...
    def get_convo_id_from_session(self, event: Event) -> str: ...
    def get_chat_bot(self): ...
    async def chat(self, event: Event, prompt: Optional[str]) -> Optional[str]: ...
